#!/usr/bin/env python

import sys
import logging
import os
from PyQt4 import QtGui, QtCore
from lib import juniper_ui

logging.basicConfig(level=logging.DEBUG)
#QtGui.QApplication.setStyle("plastique")
app = QtGui.QApplication(sys.argv)
res = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'res')
mw = juniper_ui.MainWindow(app, res)
ret = app.exec_()
app.deleteLater()
sys.exit(ret)